version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/phrase/phraseapp-client
    steps:
      - checkout
      - run: make all

  release:
    machine: true
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install realpath
      - run: ./build/release.sh

workflows:
  version: 2
  main:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
